# Generated by Django 4.1 on 2022-10-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_monthrate_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
