# Generated by Django 4.1 on 2022-10-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
