# Generated by Django 4.1 on 2022-10-10 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_month_rate_delete_monthrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AlterField(
            model_name='rate',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oy', to='main.month'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
