# Generated by Django 4.1 on 2022-10-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_complaint_user_alter_rate_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_replied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='directions',
            name='monthly_payment',
            field=models.IntegerField(),
        ),
    ]
