# Generated by Django 4.1 on 2022-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_complaint_is_replied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
