# Generated by Django 4.1 on 2022-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_complaint_is_replied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='is_replied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
